_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 48
                - 49
                - 51
                - 53
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 48
                - 49
                - 51
                - 53
                - 63
            "3":
                - 13
                - 16
                - 55
            "4": 3.10.9
            "5": 0.20.1
            "6": 4.36.2
            "12": 0.20.1
            "13": linux-x86_64
CE_CL:
    value: true
K_epochs:
    value: 3
action_size:
    value: 100
action_std:
    value: 0.5
ape:
    value: true
ape_class:
    value: false
attn:
    value: normal
chief_feature_dir:
    value: /work/data/TCGA-LUAD-FS/CHIEF/20X/pt_files(stain_norm)
cls:
    value: true
csv:
    value: /work/PAMIL_GIGAPATH_CHIEF/4_fold/LUAD/CSMD3/dataset_fold_3.csv
embed_dim:
    value: 768
feature_dim:
    value: 768
gigapath_feature_dir:
    value: /work/data/TCGA-LUAD-FS/GIGAPATH/20X/pt_files(stain_norm)
gm:
    value: cluster
in_chans:
    value: 1024
instaceclass:
    value: true
lr:
    value: 1e-05
mode:
    value: rlselect
n_classes:
    value: 2
num_epochs:
    value: 300
num_layers:
    value: 2
num_msg:
    value: 1
patience:
    value: 20
policy_conv:
    value: false
policy_hidden_dim:
    value: 768
ppo_gamma:
    value: 0.1
ppo_lr:
    value: 1e-05
reward_rule:
    value: cl
save_dir:
    value: /work/PAMIL_two_round_100/result_two_round_100//CSMD3
seed:
    value: 2021
state_dim:
    value: 768
test_dir:
    value: /work/PAMIL_GIGAPATH_CHIEF/test
test_h5:
    value: /work/data/TCGA-LUAD-FS/CHIEF/20X/h5_files(stain_norm)
test_total_T:
    value: 3
train_h5:
    value: /work/data/TCGA-LUAD-FS/CHIEF/20X/h5_files(stain_norm)
train_total_T:
    value: 3
type:
    value: tcga
